// <auto-generated />
using CrosswordCreator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrosswordCreator.Migrations
{
    [DbContext(typeof(CrosswordDbContext))]
    partial class CrosswordDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("CrosswordCreator.Data.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WordStartCol")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WordStartRow")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("CrosswordCreator.Data.Entities.Crossword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Crosswords");
                });

            modelBuilder.Entity("CrosswordCreator.Data.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrosswordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CrosswordId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("CrosswordCreator.Data.Entities.Row", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Chars")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CrosswordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CrosswordId");

                    b.ToTable("Rows");
                });

            modelBuilder.Entity("CrosswordCreator.Data.Entities.Answer", b =>
                {
                    b.HasOne("CrosswordCreator.Data.Entities.Question", "Question")
                        .WithOne("Answer")
                        .HasForeignKey("CrosswordCreator.Data.Entities.Answer", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CrosswordCreator.Data.Entities.Question", b =>
                {
                    b.HasOne("CrosswordCreator.Data.Entities.Crossword", "Crossword")
                        .WithMany("Questions")
                        .HasForeignKey("CrosswordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crossword");
                });

            modelBuilder.Entity("CrosswordCreator.Data.Entities.Row", b =>
                {
                    b.HasOne("CrosswordCreator.Data.Entities.Crossword", "Crossword")
                        .WithMany("Rows")
                        .HasForeignKey("CrosswordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crossword");
                });

            modelBuilder.Entity("CrosswordCreator.Data.Entities.Crossword", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Rows");
                });

            modelBuilder.Entity("CrosswordCreator.Data.Entities.Question", b =>
                {
                    b.Navigation("Answer")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
